version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Ctere1
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Ctere1
