package tests

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func EAPOLTest(t *testing.T, config string) ([]string, int) {
	t.Helper()
	requireEAPOLTest(t)
	requireTestAsset(t, config)
	requireTestAsset(t, filepath.Join("certs", "ca.pem"))

	tester := exec.Command(
		"eapol_test",
		"-s",
		"foo",
		"-c",
		config,
	)
	cwd, err := os.Getwd()
	assert.NoError(t, err)
	tester.Dir = cwd
	o, _ := tester.Output()
	ec := tester.ProcessState.ExitCode()
	return strings.Split(string(o), "\n"), ec
}

func requireEAPOLTest(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("eapol_test"); err != nil {
		// Locally, eapol_test is often absent so we skip to keep `go test`
		// usable. In CI it is installed on purpose, so a missing binary means
		// the integration coverage silently vanished — fail hard instead so the
		// regression is visible rather than masked by a green-but-skipped run.
		if os.Getenv("CI") != "" {
			t.Fatal("eapol_test not found on PATH but CI is set: EAP integration coverage would be skipped")
		}
		t.Skip("skipping EAP integration test: eapol_test is not installed")
	}
}

func requireTestAsset(t *testing.T, relativePath string) {
	t.Helper()
	if _, err := os.Stat(relativePath); err != nil {
		// In CI the certs are generated by `make test-cert-gen` (crtls); a
		// missing asset there is a real failure, not a reason to skip silently.
		if os.Getenv("CI") != "" {
			t.Fatalf("missing test asset %q but CI is set: EAP integration coverage would be skipped", relativePath)
		}
		t.Skipf("skipping EAP integration test: missing test asset %q", relativePath)
	}
}
